version: '3.8'
services:
   web:
       build: .
       command: python manage.py runserver 0.0.0.0:5050
       ports:
           - 5050:5050
   bot:
       build: .
       command: python telegram_bot.py
